name: openjmu
description: A JMU Flutter application.

version: 0.9.0+149

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  badges: 1.1.0
  connectivity: ^0.4.6+2
  cookie_jar: 1.0.1
  crypto: any
  dartx: ^0.2.0
  device_info: ^0.4.1+4
  dio: 2.1.16
  event_bus: 1.1.0
  extended_image: ^0.6.9
  extended_list: ^0.1.3
  extended_tabs: ^0.2.2
  extended_text: ^0.7.1
  extended_text_field: ^0.4.9
  flutter_icons: ^1.0.0+1
  flutter_inappwebview:
    git:
      url: https://github.com/AlexVincent525/flutter_inappwebview.git
      ref: "f520b822fc1c5d3c12616b8bbd6aff4c22bffc6a"
  flutter_local_notifications: 1.1.3
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git
  flutter_qr_reader: 1.0.3
  flutter_screenutil: ^1.0.2
  flutter_svg: ^0.16.1
  flutter_webview_plugin: ^0.3.10
  hive: 1.3.0
  hive_flutter: ^0.3.0+1
  html: ^0.14.0+3
  image: any
  image_editor: ^0.1.6
  image_downloader: ^0.19.1
  image_gallery_saver: 1.2.2
  image_picker: 0.6.3+1
  intl: any
  isolate: ^2.0.2
  launch_review: 2.0.0
  like_button: ^0.2.0
  multi_image_picker: 4.6.1
  oktoast: 2.3.0
  open_file: 3.0.1
  ota_update: 2.1.1
  package_info: ^0.4.0+13
  path_provider: 1.5.1
  permission_handler: 4.2.0+hotfix.2
  provider: 4.0.2
  pull_to_refresh_notification: ^0.3.3
  qr_flutter: 3.2.0
  quick_actions: ^0.4.0+1
  url_launcher: 5.4.1
  uuid: 2.0.4

dev_dependencies:
  build_runner: ^1.7.3
  flutter_test:
    sdk: flutter
  ff_annotation_route: ^1.1.5
  hive_generator: ^0.7.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/emotionIcons/
    - assets/icons/
    - assets/icons/addButton/
    - assets/icons/appCenter/
    - assets/icons/bottomNavigation/
    - assets/icons/gender/
    - assets/icons/postActions/
    - assets/icons/settings/
    - images/
    - images/placeholder/
  fonts:
    - family: chocolate
      fonts:
        - asset: assets/fonts/chocolate.ttf
