name: OpenJMU
description: A JMU Flutter application.

version: 0.3.7+29

environment:
    sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    badges: ^0.0.6
    cached_network_image: ^0.7.0
    cookie_jar: ^1.0.0
#    connectivity: ^0.4.3
    crypto: ^2.0.6
    dio: ^2.1.2
    dragablegridview_flutter: ^0.1.6
    event_bus: ^1.1.0
    extended_image: ^0.2.9
    extended_tabs: ^0.1.6
    extended_text: ^0.3.3
    image_downloader: ^0.14.1
    fluttertoast: ^3.0.4
    flutter_cache_manager: ^0.3.2
    flutter_colorpicker: ^0.2.3
    flutter_local_notifications: ^0.6.1
    flutter_platform_widgets: ^0.9.5
    flutter_webview_plugin: ^0.3.4
    flutter_svg: ^0.12.4
    multi_image_picker: ^4.2.0
    ota_update: ^1.0.2
    package_info: ^0.4.0+3
    shared_preferences: ^0.5.2
    uuid: ^2.0.1

dev_dependencies:
    flutter_test:
        sdk: flutter


flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/emotionIcons/
        - assets/icons/
        - assets/icons/webApps/
        - images/
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700