name: openjmu
description: A JMU Flutter application.
homepage: https://github.com/openjmu/OpenJMU
version: 1.2.3+257
publish_to: 'none'

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.6"

dependencies:
  analyzer: 1.5.0
  animations: ^2.0.0
  badges: ^2.0.1
  connectivity_plus: ^1.0.1
  cookie_jar: ^3.0.1
  dartx: ^0.7.1
  device_info_plus: ^1.0.1
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  equatable: ^2.0.2
  event_bus: ^2.0.0
  extended_image: ^4.1.0
  extended_list: ^3.0.0
  extended_nested_scroll_view: ^3.0.0
  extended_tabs: ^2.2.0
  extended_text: ^7.0.0
  extended_text_field: ^8.0.0
  ff_annotation_route_library: ^2.0.1
  flutter:
    sdk: flutter
  flutter_displaymode: 0.3.2
  flutter_inappwebview: ^5.3.2
  flutter_local_notifications: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_image:
    git:
      url: https://github.com/AlexV525/flutter_native_image.git
      ref: e80174ceff91c8c5e5a0826f24f143ab2ce3ae24
  flutter_screenutil:
    git:
      url: https://github.com/Alexv525/flutter_screenutil.git
      ref: c04266e796820f5bde6aca1c48f9409a4b5ce61d
  flutter_svg: ^0.22.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  html: ^0.15.0
  image: ^3.0.2
  image_editor: ^1.0.0
  isolate: ^2.0.2
  like_button: ^2.0.2
  loading_more_list: ^4.0.0
  oktoast: ^3.0.0
  open_file: ^3.2.1
  package_info_plus: ^1.0.1
  permission_handler: ^7.2.0
  provider: ^5.0.0
  pull_to_refresh_notification: ^2.0.1
  qr_flutter: ^4.0.0
  r_scan:
    git:
      url: https://github.com/AlexV525/r_scan.git
      ref: 5cd2f74e
  url_launcher: ^6.0.6
  uuid: ^3.0.4
  vibration: ^1.7.4-nullsafety.0
  video_player: ^2.1.5
  wechat_assets_picker: ^5.5.3+1
  wechat_camera_picker: ^2.2.0

dev_dependencies:
  build_runner: ^2.0.4
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/emoji/
    - assets/icons/
    - assets/icons/add-button/
    - assets/icons/app-center/
    - assets/icons/app-center/apps/
    - assets/icons/bottom-navigation/
    - assets/icons/gender/
    - assets/icons/post-actions/
    - assets/icons/publish/
    - assets/icons/self-page/
    - assets/icons/settings/
    - assets/icons/tutorial/
    - assets/icons/user/
    - assets/placeholders/
    - images/
  fonts:
    - family: "chocolate"
      fonts:
        - asset: assets/fonts/chocolate.ttf
    - family: "JetBrains Mono"
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
