name: openjmu
description: A JMU Flutter application.

version: 1.0.0+185

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  badges: 1.1.0
  connectivity: ^0.4.8+5
  cookie_jar: 1.0.1
  device_info: ^0.4.1+4
  dio:
    git:
      url: https://github.com/AlexVincent525/dio.git
      ref: v2.1.16
      path: package_src
  event_bus: 1.1.1
  extended_image: 0.7.3+1
  extended_list: ^0.1.5
  extended_tabs: ^0.2.2
  extended_nested_scroll_view: ^0.4.0
  extended_text: ^0.7.1
  extended_text_field: ^0.5.0
  flutter_displaymode:
    git:
      url: https://github.com/AlexVincent525/flutter_displaymode.git
      ref: "538c10ff"
  flutter_icons: ^1.1.0
  flutter_inappwebview: 3.1.0
  flutter_local_notifications: 1.1.3
  flutter_native_image: ^0.0.5
  flutter_screenutil: ^1.1.0
  flutter_spinkit: 4.1.2+1
  flutter_svg: ^0.17.4
  flutter_webview_plugin: ^0.3.10
  hive: 1.3.0
  hive_flutter: ^0.3.0+1
  html: ^0.14.0+3
  image_editor: ^0.1.6
  image_gallery_saver: 1.2.2
  image_picker: 0.6.3+1
  image_save: 2.1.0
  isolate: ^2.0.2
  launch_review: 2.0.0
  like_button: ^0.2.0
  multi_image_picker: 4.6.1
  oktoast: 2.3.1
  open_file: 3.0.1
  package_info: ^0.4.0+17
  path_provider: 1.6.7
  permission_handler: 5.0.0+hotfix.6
  provider: 4.1.2
  pull_to_refresh_notification: ^0.3.4
  qr_flutter: 3.2.0
  quick_actions: ^0.4.0+4
  r_scan: 0.1.4+1
  url_launcher: 5.4.5
  uuid: 2.0.4
  wechat_assets_picker: ^1.6.0

dev_dependencies:
  build_runner: ^1.7.3
  extended_image_library: any
  ff_annotation_route: ^2.1.0
  flutter_asset_generator: ^0.4.6
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0

dependency_overrides:
  crypto: 2.1.4
  dartx: ^0.3.0
  image: 2.1.12
  intl: ^0.16.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/emotion-icons/
    - assets/icons/
    - assets/icons/add-button/
    - assets/icons/app-center/
    - assets/icons/bottom-navigation/
    - assets/icons/gender/
    - assets/icons/post-actions/
    - assets/icons/self-page/
    - assets/icons/settings/
    - images/
    - images/placeholder/
  fonts:
    - family: "chocolate"
      fonts:
        - asset: assets/fonts/chocolate.ttf
    - family: "JetBrains Mono"
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
